apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: circleci-container-runner
spec:
  collectors:
    - logs:
        selector:
          - app=container-agent
        name: container-agent
        limits:
          maxAge: 72h
          maxLines: 1000
    - logs:
        selector:
          - app.kubernetes.io/name=circleci-task-agent
          - app.kubernetes.io/managed-by=circleci-container-agent
        name: container-task
    - exec:
        name: runner_api
        selector:
          - app.kubernetes.io/managed-by=circleci-container-agent
        command:
          - /bin/sh
          - -c
          - "RUNNER_API_HOST=$(echo $RUNNER_API | cut -d'/' -f3); wget $RUNNER_API_HOST/api/v3/runner?namespace=foobar"
        timeout: 10s
  redactors:
    - name: JSON Redactor
      fileSelector:
        files:
        - cluster-resources/*.json
        - cluster-resources/pods/*.json
        - cluster-resources/services/*.json
        - cluster-resources/deployments/*.json
        # Add more paths as needed
      removals:
        - regex:
          - selector: CIRCLECI_RUNNER_API_AUTH_TOKEN
            redactor: '("value": ")(?P<mask>.*)(")'
        - regex:
          - selector: CIRCLE_GOAT_CONFIG
            redactor: '("value": ")(?P<mask>.*)(")'
  analyzers: []